apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: k3d-my-cluster-registry:5000/influxdb:2.7
          ports:
            - containerPort: 8086
          env:
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: "setup"
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              value: "admin"
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              value: "sensor_password"
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: "sensor_hq"
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: "sensor_data"
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sensor-secret
                  key: INFLUXDB_TOKEN
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
spec:
  selector:
    app: influxdb
  ports:
    - port: 8086
      targetPort: 8086
